//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EasyCash.rc
//
#define IDC_MINUS                       2
#define IDC_VERWERFEN                   3
#define IDC_UP                          3
#define IDC_SPLIT                       3
#define IDC_BERECHNEN                   3
#define IDC_RECHNER                     4
#define IDC_DOWN                        4
#define IDC_MINUS2                      5
#define IDC_UP2                         6
#define IDC_DOWN2                       7
#define IDC_AENDERN2                    9
#define IDD_ABOUTBOX                    100
#define IDB_LIGHTBULB                   102
#define IDD_TIP                         103
#define CG_IDS_TIPOFTHEDAY              104
#define CG_IDS_TIPOFTHEDAYMENU          105
#define CG_IDS_DIDYOUKNOW               106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDP_FILE_CORRUPT             108
#define CG_IDS_TIPOFTHEDAYHELP          109
#define IDS_CSVIMPORT_INSTABIL          110
#define IDS_EASYRTX_INSTABIL            111
#define IDS_EASYCTX_FEHLT               112
#define IDS_CAPTION_IMAGE_TIP           113
#define IDR_HTML_FORMULARABSCHNITT      114
#define IDS_OLEINIT                     114
#define IDS_FORMULARDRUCK_DE            115
#define IDR_MAINFRAME                   128
#define IDR_EASYCATYPE                  129
#define IDD_BUCHUNG                     130
#define IDR_EASYCAREGTYPE               130
#define IDD_DAUERBUCHUNGEN              131
#define IDD_DAUERBUCHUNGEN_AUSFUEHREN   132
#define IDB_BUTTON1                     324
#define IDB_STOP                        325
#define IDB_SPIKE                       326
#define IDB_31STER                      329
#define IDB_31STER_AUSHUEHREN           330
#define IDB_31STER_AUSFUEHREN_GROSS     332
#define IDB_INFOSIGN                    333
#define IDB_SPIKE_PLUS                  334
#define IDB_SPIKE_MINUS                 335
#define IDD_REGISTRIEREN                337
#define IDD_REGISTER_DIALOG             338
#define IDD_DRUCKAUSWAHL                339
#define IDR_MENU1                       340
#define IDD_EINSTELLUNGEN1              341
#define IDD_EINSTELLUNGEN2              342
#define IDD_EINSTELLUNGEN3              343
#define IDD_VORANMELDUNGSZEITRAUM       344
#define IDB_CLOCK                       346
#define IDB_SPANNER                     347
#define IDB_UP                          348
#define IDD_EINSTELLUNGEN4              349
#define IDB_DOWN                        349
#define IDB_PLUS                        350
#define IDB_MINUS                       351
#define IDD_NEUES_KONTO                 351
#define IDB_PIE                         354
#define IDD_EINSTELLUNGEN5              355
#define IDI_FACE1                       356
#define IDI_FACE2                       357
#define IDI_FACE3                       358
#define IDD_VOTE                        359
#define IDB_AENDERN                     361
#define IDR_PLUGIN                      369
#define IDD_PLUGIN_MANAGER              371
#define IDB_PLUGIN_PLATZHALTER          376
#define IDB_EASYCASH                    377
#define IDB_RECHNER                     378
#define IDD_RECHNER                     379
#define IDD_RECHN                       380
#define IDD_NEUES_FORMULAR              382
#define IDD_FORMULARFELD                383
#define IDD_VORANMELDUNGSZEITRAUM_DROPLIST 386
#define IDR_FIND                        389
#define IDD_ICONAUSWAHL                 391
#define IDD_ICONAUSWAHL_MANDANT         391
#define IDB_ICONS                       404
#define IDD_MANDANT_NAME                405
#define IDB_HICOLOR_TOOLBAR             406
#define IDD_ICONAUSWAHL_BETRIEB         406
#define IDB_HICOLOR_TOOLBAR_DISABLED    407
#define IDD_ICONAUSWAHL_BESTANDSKONTO   407
#define IDB_HICOLOR_TOOLBAR_HOT         408
#define IDB_ICONS_BESTANDSKONTEN        409
#define IDD_UNTERNEHMENSART             410
#define IDD_ANFANGSSALDO                411
#define IDD_DATENVERZEICHNIS            412
#define IDB_DATENVERZEICHNIS            413
#define IDD_USTVORAUSZAHLUNGEN          414
#define IDD_FORMULARABSCHNITT           415
#define IDB_TOOLBAR_16                  419
#define IDB_TOOLBAR_32                  420
#define IDR_DAUERBUCHUNGEN_AUSFUEHREN_MONATE 421
#define IDR_JOURNALANSICHT              423
#define IDR_FILTER_MONAT                424
#define IDR_FILTER_KONTO                425
#define IDR_JOURNALDRUCK                426
#define IDR_FILTER_KONTO1               427
#define IDR_ANSICHT_FORMULARE           427
#define IDB_BIG_ICON_CHECKMARK          428
#define IDR_ANSICHT_PLUGINS             428
#define IDB_TOOLBAR_EINSTELLUNGEN_32    429
#define IDB_TOOLBAR_EINSTELLUNGEN_16    430
#define IDR_THEME_MENU                  431
#define IDB_BITMAP1                     433
#define IDB_EASYCASH_32                 433
#define IDB_INFO                        434
#define IDR_ZOOMFAKTOR                  436
#define IDR_RIBBON                      438
#define IDC_DATUM_TAG                   1000
#define IDC_BULB                        1000
#define IDC_DATUM_MONAT                 1001
#define IDC_STARTUP                     1001
#define IDC_MRU_CAPTION                 1001
#define IDC_DATUM_JAHR                  1002
#define IDC_NEXTTIP                     1002
#define IDC_ERGEBNISSE_LBOX             1002
#define IDC_MRU_COMBO                   1002
#define IDC_BESCHREIBUNG                1003
#define IDC_MWST                        1004
#define IDC_TIPSTRING                   1004
#define IDC_VARIABLEN_LBOX              1004
#define IDC_BETRAG                      1005
#define IDC_FUNKTIONEN_LBOX             1005
#define IDC_ABSCHREIBUNGJAHRE           1006
#define IDC_ABSCHREIBUNGJAHRE_STATIC    1007
#define IDC_STATUS                      1007
#define IDC_EINNAHMEN                   1008
#define IDC_AUSGABEN                    1009
#define IDC_LIST                        1010
#define IDC_REG_EDIT                    1010
#define IDC_BELEGNUMMER                 1010
#define IDC_DATUM_BIS_MONAT             1011
#define IDC_MAKE_NR                     1011
#define IDC_ABSCHREIBUNGRESTWERT_STATIC 1011
#define IDC_DATUM_BIS_JAHR              1012
#define IDC_ABSCHREIBUNGRESTWERT        1012
#define IDC_DATUM_VON_MONAT             1013
#define IDC_ABSCHREIBUNG_GENAUIGKEIT_STATIC 1013
#define IDC_DATUM_VON_JAHR              1014
#define IDC_ABSCHREIBUNG_GENAUIGKEIT    1014
#define IDC_MONATLICH                   1015
#define IDC_ABSCHREIBUNGJAHRE2          1015
#define IDC_ABSCHREIBUNGNUMMER          1015
#define IDC_QUARTALSMAESSIG             1016
#define IDC_ABSCHREIBUNGJAHRE_STATIC2   1016
#define IDC_Neu                         1017
#define IDC_AENDERN                     1018
#define IDC_ERNST                       1018
#define IDC_PROPERTY                    1018
#define IDC_LOESCHEN                    1019
#define IDC_EMAIL                       1019
#define IDC_HALBJAEHRLICH               1020
#define IDC_WWW                         1020
#define IDC_ICON_AENDERN                1020
#define IDC_JAEHRLICH                   1021
#define IDC_REGISTER                    1021
#define IDC_REG_STRING                  1022
#define IDC_DATUM_AKT_MONAT             1022
#define IDC_BUCHUNGSLISTE               1023
#define IDC_DATUM_AKT_JAHR              1023
#define IDC_WWW2                        1023
#define IDC_GITHUB                      1023
#define IDC_UMST_VORANMELDUNG           1024
#define IDC_2MONATLICH                  1024
#define IDC_UMST_ERKLAERUNG             1025
#define IDC_BELEGNUMMER2                1025
#define IDC_EKST_ERKLAERUNG             1026
#define IDC_TAEGLICH_BUCHEN             1026
#define IDC_EURECHNUNG                  1026
#define IDC_EKST_ANLAGE_GSE             1027
#define IDC_NAME                        1027
#define IDC_BUCHUNGSLISTE_KONTEN        1027
#define IDC_BUCHUNGSDATUM_BELASSEN      1027
#define IDC_VORNAME                     1028
#define IDC_MONAT                       1028
#define IDC_ID                          1028
#define IDC_ANZEIGENAME                 1028
#define IDC_UMST_ERKLAERUNG2            1028
#define IDC_ANLAGENVERZEICHNIS          1028
#define IDC_EURECHNUNG_FORMULAR         1029
#define IDC_UNTERNEHMENSART1            1029
#define IDC_QUARTAL                     1029
#define IDC_NAME2                       1029
#define IDC_SCHRIFTART                  1029
#define IDC_UNTERNEHMENSART2            1030
#define IDC_QUARTALMONAT                1030
#define IDC_STRASSE                     1031
#define IDC_TESTVERSION                 1031
#define IDC_PLZ                         1032
#define IDC_ORT                         1033
#define IDC_LISTE                       1033
#define IDC_STEUERNUMMER                1034
#define IDC_BUCHUNGSPOSTENTEXT          1034
#define IDC_VAT1                        1034
#define IDC_BUCHUNGSPOSTENNUMMER        1035
#define IDC_VAT2                        1035
#define IDC_LAUFENDE_BUCHUNGSNUMMERN_FUER_EINNAHMEN 1036
#define IDC_VAT3                        1036
#define IDC_LAUFENDE_BUCHUNGSNUMMERN_FUER_AUSGABEN 1037
#define IDC_VAT4                        1037
#define IDC_EA                          1038
#define IDC_VERSION                     1039
#define IDC_LAUFENDE_BUCHUNGSNUMMERN_FUER_BANK 1039
#define IDC_AFA                         1040
#define IDC_EURECHNUNGSPOSTEN           1041
#define IDC_HORIZONTALE_VERSCHIEBUNG    1042
#define IDC_LAUFENDE_BUCHUNGSNUMMERN_FUER_KASSE 1042
#define IDC_VERTIKALE_VERSCHIEBUNG      1043
#define IDC_LISTE_EINNAHMEN             1043
#define IDC_PLUS                        1044
#define IDC_HORIZONTALE_VERSCHIEBUNG2   1044
#define IDC_KONTO                       1045
#define IDC_LISTE_AUSGABEN              1045
#define IDC_SONDERVORAUSZAHLUNG         1045
#define IDC_PLUS2                       1046
#define IDC_LAND1                       1046
#define IDC_BIC                         1046
#define IDC_LAND2                       1047
#define IDC_LAND3                       1048
#define IDC_KONTAKT_EMAIL               1048
#define IDC_KONTAKT_REGISTRIERCODE      1049
#define IDC_LFD_BUCHUNGSNUMMER_EINNAHMEN 1049
#define IDC_LFD_BUCHUNGSNUMMER_AUSGABEN 1050
#define IDC_VOTE                        1050
#define IDC_LFD_BUCHUNGSNUMMER_EINNAHMEN_JAHR 1051
#define IDC_LFD_BUCHUNGSNUMMER_AUSGABEN_JAHR 1052
#define IDC_JAHR                        1053
#define IDC_LFD_BUCHUNGSNUMMER_EINNAHMEN_JAHR2 1053
#define IDC_USTVST_GESONDERT            1054
#define IDC_LFD_BUCHUNGSNUMMER_BANK     1054
#define IDC_DATUM_VON_TAG               1055
#define IDC_NACH_KONTEN_SEITENUMBRUCH   1055
#define IDC_LFD_BUCHUNGSNUMMER_AUSGABEN_JAHR2 1055
#define IDC_DATUM_BIS_TAG               1056
#define IDC_LFD_BUCHUNGSNUMMER_KASSE    1056
#define IDC_BILDSCHIRMSCHRIFT           1057
#define IDC_DRUCKERSCHRIFT              1058
#define IDC_JAHR_ENABLED                1058
#define IDC_AFA_GENAUIGKEIT             1059
#define IDC_JAHR_ENABLED2               1059
#define IDC_MWST_ENABLED                1059
#define IDC_KONVERTIEREN                1074
#define IDC_RADIO1                      1075
#define IDC_RADIO2                      1076
#define IDC_RADIO3                      1077
#define IDC_RADIO4                      1078
#define IDC_PUNKT                       1079
#define IDC_ART1                        1080
#define IDC_SATZ1                       1081
#define IDC_ART2                        1082
#define IDC_SATZ2                       1083
#define IDC_BLZ                         1083
#define IDC_ART3                        1084
#define IDC_BANK                        1084
#define IDC_TEXT                        1084
#define IDC_SATZ3                       1085
#define IDC_MERKEN                      1085
#define IDC_IBAN                        1085
#define IDC_ART4                        1086
#define IDC_FORMULAR_NICHT_MITDRUCKEN   1086
#define IDC_SATZ4                       1087
#define IDC_HINWEIS                     1087
#define IDC_ART5                        1088
#define IDC_SATZ5                       1089
#define IDC_ART6                        1090
#define IDC_SATZ6                       1091
#define IDC_BUCHUNGSJAHR                1091
#define IDC_ART7                        1092
#define IDC_KONTENFILTER                1092
#define IDC_SATZ7                       1093
#define IDC_EINNAHMEN_GEGENKONTO        1093
#define IDC_ART8                        1094
#define IDC_SATZ8                       1095
#define IDC_ART9                        1096
#define IDC_EINGABE                     1096
#define IDC_SATZ9                       1097
#define IDC_ERGEBNIS                    1097
#define IDC_ART10                       1098
#define IDC_SATZ10                      1099
#define IDC_FORMEL1                     1099
#define IDC_USTSATZ1                    1100
#define IDC_FORMEL2                     1100
#define IDC_USTSATZ2                    1101
#define IDC_FORMEL3                     1101
#define IDC_USTSATZ3                    1102
#define IDC_FORMEL4                     1102
#define IDC_USTSATZ4                    1103
#define IDC_USTSATZ5                    1104
#define IDC_UEBERNEHMEN                 1104
#define IDC_USTSATZ6                    1105
#define IDC_USTSATZ7                    1106
#define IDC_FORMEL5                     1106
#define IDC_KONTENKATEGORIE             1106
#define IDC_USTSATZ8                    1107
#define IDC_FORMEL6                     1107
#define IDC_FORMULAR                    1107
#define IDC_FELDZUWEISUNG               1107
#define IDC_USTSATZ9                    1108
#define IDC_FORMEL7                     1108
#define IDC_FORMULARNAME                1108
#define IDC_FINANZAMTSZAHLUNGEN1        1108
#define IDC_USTSATZ10                   1109
#define IDC_FORMEL8                     1109
#define IDC_KATEGORIE                   1109
#define IDC_FINANZAMTSZAHLUNGEN2        1109
#define IDC_FORMEL9                     1110
#define IDC_FORMEL10                    1111
#define IDC_DATEINAME                   1112
#define IDC_SEITEN                      1113
#define IDC_LANGFORM                    1113
#define IDC_GRAFIKDATEIEN               1114
#define IDC_SCHRIFTGROESSE              1115
#define IDC_SEITE                       1116
#define IDC_SEITE_SPIN                  1117
#define IDC_HORIZONTAL                  1118
#define IDC_HORIZONTAL_SPIN             1119
#define IDC_VERTIKAL                    1120
#define IDC_VERTIKAL_SPIN               1121
#define IDC_TYP                         1122
#define IDC_AUSRICHTUNG                 1123
#define IDC_AUSRICHTUNG2                1124
#define IDC_ANTEIL                      1125
#define IDC_ANTEIL2                     1126
#define IDC_ANTEIL3                     1127
#define IDC_NACHKOMMAANTEIL             1128
#define IDC_NACHKOMMAANTEIL2            1129
#define IDC_NULLWERTE                   1130
#define IDC_MOUSEPOS                    1131
#define IDC_NULLWERTE2                  1132
#define IDC_COMBO                       1133
#define IDC_VERALTET                    1133
#define IDC_UEBERTRAGEN                 1134
#define IDC_VERALTET2                   1134
#define IDC_FELDZUWEISUNG_LOESCHEN      1135
#define IDC_ICONLISTE                   1136
#define IDC_BITTE                       1137
#define IDC_NEUER_MANDANT               1139
#define IDC_MANDANT_LOESCHEN            1140
#define IDC_MANDANT_UMBENENNEN          1142
#define IDC_UMBENENNEN                  1143
#define IDC_BETRIEB_STATIC              1145
#define IDC_BESTANDSKONTO_STATIC        1146
#define IDC_BETRIEB                     1147
#define IDC_BESTANDSKONTO               1148
#define IDC_ANFANGSSALDO                1148
#define IDC_ALT1                        1149
#define IDC_ALT2                        1150
#define IDC_ALT3                        1151
#define IDC_ALT4                        1152
#define IDC_BETRIEBFILTER               1152
#define IDC_ALT5                        1153
#define IDC_Q1                          1153
#define IDC_ALT6                        1154
#define IDC_M1                          1154
#define IDC_M2                          1155
#define IDC_USTVST_GESONDERT_STATIC     1155
#define IDC_M3                          1156
#define IDC_BUTTON1                     1156
#define IDC_MANUELLER_DOWNLOAD          1156
#define IDC_ABGANG_BUCHEN               1156
#define IDC_Q2                          1157
#define IDC_M4                          1158
#define IDC_STATIC_INFO                 1158
#define IDC_M5                          1159
#define IDC_UNTERKATEGORIE              1159
#define IDC_M6                          1160
#define IDC_VON_STATIC                  1160
#define IDC_DATUM_VON_STATIC            1160
#define IDC_Q3                          1161
#define IDC_DATUM_BIS_STATIC            1161
#define IDC_M7                          1162
#define IDC_DATUM_TAG_STATIC            1162
#define IDC_M8                          1163
#define IDC_DATUM_AKT_STATIC            1163
#define IDC_M9                          1164
#define IDC_BETRAG_STATIC               1164
#define IDC_Q4                          1165
#define IDC_BESCHREIBUNG_STATIC         1165
#define IDC_M10                         1166
#define IDC_BELEGNUMMER2_STATIC         1166
#define IDC_M11                         1167
#define IDC_PLATZHALTER_STATIC          1167
#define IDC_M12                         1168
#define IDC_EURECHNUNGSPOSTEN_STATIC    1168
#define IDC_VORAUSZAHLUNG               1169
#define IDC_MWST_STATIC                 1169
#define IDC_REPARATURINSTALLATION       1170
#define IDC_BUCHUNGSLISTE_BESTANDSKONTEN 1500
#define ID_VIEW_JOURNAL_MONATE_ALLE     2802
#define ID_VIEW_JOURNAL_MONATE_JANUAR   2803
#define ID_VIEW_JOURNAL_MONATE_FEBRUAR  2804
#define ID_VIEW_JOURNAL_MONATE_MAERZ    2805
#define ID_VIEW_JOURNAL_MONATE_APRIL    2806
#define ID_VIEW_JOURNAL_MONATE_MAI      2807
#define ID_VIEW_JOURNAL_MONATE_JUNI     2808
#define ID_VIEW_JOURNAL_MONATE_JULI     2809
#define ID_VIEW_JOURNAL_MONATE_AUGUST   2810
#define ID_VIEW_JOURNAL_MONATE_SEPTEMBER 2811
#define ID_VIEW_JOURNAL_MONATE_OKTOBER  2812
#define ID_VIEW_JOURNAL_MONATE_NOVEMBER 2813
#define ID_VIEW_JOURNAL_MONATE_DEZEMBER 2814
#define ID_VIEW_JOURNAL_MONATE_QUARTAL1 2815
#define ID_VIEW_JOURNAL_MONATE_QUARTAL2 2816
#define ID_VIEW_JOURNAL_MONATE_QUARTAL3 2817
#define ID_VIEW_JOURNAL_MONATE_QUARTAL4 2818
#define ID_EDIT_EINNAHME_BUCHEN         32771
#define ID_EDIT_AUSGABE_BUCHEN          32772
#define ID_EDIT_AUSGABE_BUCHEN2         32772
#define ID_EDIT_DAUERBUCHUNGEN_EINGEBEN 32773
#define ID_EDIT_DAUERBUCHUNGEN_AUSFUEHREN 32774
#define ID_FILE_JAHRESWECHSEL           32775
#define ID_VIEW_OPTIONS                 32780
#define ID_BUTTON32782                  32782
#define ID_FILE_EXPORT                  32783
#define ID_BUTTON32784                  32784
#define ID_VIEW_JOURNAL_DATUM           32785
#define ID_VIEW_JOURNAL_KONTEN          32786
#define ID_VIEW_JOURNAL_SWITCH          32788
#define ID_VIEW_PLUGINTOOLBAR           32798
#define ID_FILE_PLUGINMANAGER           32799
#define IDC_DUMMY                       32815
#define ID_FORMULAR_NEU                 32816
#define ID_FILE_PRINT2                  32817
#define ID_NEXT                         32819
#define ID_PREV                         32820
#define ID_BUTTON32822                  32822
#define ID_VIEW_FINDTOOLBAR             32823
#define ID_FILE_MANDANTEN               32824
#define ID_FILE_BETRIEBE                32825
#define ID_VIEW_JOURNAL_BETRIEB         32825
#define ID_FILE_OEFFNE_DATENVERZEICHNIS 32827
#define ID_FILE_WAEHLE_DATENVERZEICHNIS 32829
#define ID_FILE_BESTANDSKONTEN          32830
#define ID_FILE_REGISTRIERUNGSINFORMATIONEN_WIEDERHERSTELLEN 32830
#define ID_VIEW_JOURNAL_BESTANDSKONTO   32831
#define ID_VIEW_JOURNAL_BESTANDSKONTEN  32832
#define ID_VIEW_JOURNAL_BESTKONTEN      32832
#define ID_FILE_BACKUP                  32833
#define ID_FILE_REGISTRIERUNGSINFORMATIONEN_SICHERN 32834
#define ID_EDIT_UMSATZSTEUERVORAUSZAHLUNGEN 32835
#define ID_ANSICHT_BLUETHEME            32836
#define ID_ANSICHT_BLACKTHEME           32837
#define ID_ANSICHT_SILVERTHEME          32838
#define ID_ANSICHT_AQUATHEME            32839
#define ID_VIEW_APPLOOK_2007            32840
#define ID_VIEW_APPLOOK_2007_1          32841
#define ID_VIEW_APPLOOK_2007_2          32842
#define ID_VIEW_APPLOOK_2007_3          32843
#define ID_VIEW_APPLOOK_2003            32844
#define ID_VIEW_APPLOOK_2005            32845
#define ID_BUCHEN_DAUAUS_MONAT0MAERZ    32846
#define ID_BUCHEN_DAUAUS_JANUAR         32847
#define ID_BUCHEN_DAUAUS_FEBRUAR        32848
#define ID_BUCHEN_DAUAUS_MAERZ          32849
#define ID_BUCHEN_DAUAUS_APRIL          32850
#define ID_BUCHEN_DAUAUS_MAI            32851
#define ID_BUCHEN_DAUAUS_JUNI           32852
#define ID_BUCHEN_DAUAUS_JULI           32853
#define ID_BUCHEN_DAUAUS_AUGUST         32854
#define ID_BUCHEN_DAUAUS_SEPTEMBER      32855
#define ID_BUCHEN_DAUAUS_OKTOBER        32856
#define ID_BUCHEN_DAUAUS_NOVEMBER       32857
#define ID_BUCHEN_DAUAUS_DEZEMBER       32858
#define ID_ANSICHT_JOURNALNURF32859     32859
#define ID_VIEW_JOURNAL_MONAT           32860
#define ID_ANSICHT_FILTERAUFN32861      32861
#define ID_VIEW_JOURNAL_KONTO           32862
#define ID_ANSICHT_FORMULARE            32865
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   32866
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  32867
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 32868
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   32869
#define ID_VIEW_APPLOOK_2007_4          32870
#define ID_EINSTELLUNGEN_DOKU           32871
#define ID_EINSTELLUNGEN_FAQ            32872
#define ID_EINSTELLUNGEN_BUGTRACKER     32873
#define ID_EINSTELLUNGEN_EMAIL          32874
#define ID_EINSTELLUNGEN_PGP            32875
#define ID_EINSTELLUNGEN_KONTAKT        32876
#define ID_TIPP_DES_TAGES_JETZT         32877
#define ID_TIPP_DES_TAGES_PROGRAMMSTART 32878
#define ID_TIPP_DES_TAGES_EMAIL         32879
#define ID_EINSTELLUNGEN_SPENDE_BANK    32880
#define ID_EINSTELLUNGEN_SPENDE_PAYPAL  32881
#define ID_EINSTELLUNGEN_SPENDE_BITCOIN 32882
#define ID_FILE_BACKUP_EXTERNAL         32883
#define ID_FILE_BACKUP_SUBFOLDER        32884
#define ID_EINSTELLUNGEN_SPENDE_FLATTR  32885
#define ID_ANSICHT_ZOOM                 32886
#define ID_ANSICHT_ZOOM_SWITCH          32887
#define ID_VIEW_ZOOM_SWITCH             32888
#define ID_VERGR32889                   32889
#define ID_ZOOMFAKTOR_VERGROESSERN      32890
#define ID_VERKLEINERN                  32891
#define ID_ZOOMFAKTOR_VERKLEINERN       32892
#define ID_50                           32893
#define ID_ZOOMFAKTOR_50                32894
#define ID_75                           32895
#define ID_ZOOMFAKTOR_75                32896
#define ID_100                          32897
#define ID_ZOOMFAKTOR_100               32898
#define ID_125                          32899
#define ID_ZOOMFAKTOR_125               32900
#define ID_150                          32901
#define ID_ZOOMFAKTOR_150               32902
#define ID_175                          32903
#define ID_ZOOMFAKTOR_175               32904
#define ID_200                          32905
#define ID_ZOOMFAKTOR_200               32906
#define ID_250                          32907
#define ID_ZOOMFAKTOR_250               32908
#define ID_300                          32909
#define ID_ZOOMFAKTOR_300               32910
#define ID_SEP                          32911
#define ID_DUMMY                        32912
#define ID_FORMULAR_INFO                32913
#define ID_ANLAGENVERZEICHNIS           32914
#define ID_VIEW_JOURNAL_ANLAGENVERZEICHNIS 32915
#define ID_FORMULARE_                   32916
#define ID_FORMULAR_MENUUPDATE          32917
#define ID_CMD_CUSTOM_MRU               48000
#define ID_STATUS                       61445
#define ID_SALDO                        61446
#define IDS_ZEIGE_PLUGIN_MANAGER        61447
#define ID_FINDCOMBO                    61448

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        442
#define _APS_NEXT_COMMAND_VALUE         32918
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
