// IconKatalog.cs -- Namen der Icons in den Sprite-Bitmaps.
//
// Gespiegelt aus den statischen IconInfo-Arrays in IconAuswahlBetrieb.cpp
// und IconAuswahlBestandskonto.cpp (der alte MFC-Pfad behält seine eigenen
// Arrays -- bei neuen Icons müssen beide Seiten ergänzt werden).
// Die Reihenfolge entspricht der Icon-Position im jeweiligen Sprite
// (icons.bmp bzw. icons_bestandskonten.bmp).

namespace ECTViews.Stammdaten
{
    internal static class IconKatalog
    {
        internal static readonly string[] Betriebe =
        {
            "Standard",
            "Einkaufstüte",
            "Kiste",
            "Glas",
            "Zettel",
            "Füller",
            "Bleistift",
            "Tresor",
            "Schreibmaschine",
            "Notizblock",
            "CD",
            "Festplatte",
            "Maus",
            "Computer",
            "Notebook",
            "Platine",
            "Wassermann",
            "Schaf",
            "Krebs",
            "Schütze",
            "Skorpion",
            "Drache",
            "Möbel",
            "Tor",
            "Obst",
            "Brot",
            "Käse",
            "Kreuz",
            "Geschenk",
            "Kranz",
            "Kosmetik",
            "Schuh",
            "Handy",
            "Uhr",
            "Kaktus",
            "Kerze",
            "Wecker",
            "Zauberei",
            "Bügeleisen",
            "Video",
            "Medikament",
            "Ente",
            "Spielzeug",
            "Mikrofon",
            "Keyboard",
            "Trommel",
            "Lautsprecher",
            "Hund",
            "Schädel",
            "Vogel",
            "Fisch",
            "Internet",
            "Ausrufungszeichen",
            "Hütchen",
            "Leuchtturm",
            "Pinsel",
            "Ziegel",
            "Teppichmesser",
            "Ölkanne",
            "Träger",
            "Zange",
            "Globus",
            "Qualle",
            "Schwamm",
            "Mond",
            "Rakete",
            "Trepanation",
            "Bär",
            "Papierkrieg",
            "Solar"
        };

        internal static readonly string[] Bestandskonten =
        {
            // Allgemein
            "cash",
            "bar",
            "Kasse",
            // Banken
            "SozialBank",
            "Citibank",
            "comdirect",
            "Commerzbank",
            "apoBank (Deutschland)",
            "Deutsche Bank",
            "DAB (Legacy)",
            "Dresdner Bank (Legacy)",
            "Volks- und Raiffeisenbanken",
            "HypoVereinsbank / Bank Austria",
            "ING-DiBa",
            "NetBank (Legacy)",
            "NIBC Bank",
            "Noa Bank (Legacy)",
            "norisbank",
            "Postbank",
            "PSD-Bank",
            "Santander Consumer Bank",
            "SEB",
            "Sparda-Bank (Deutschland)",
            "Raiffeisen (Österreich)",
            "Volksbank",
            "Sparkasse",
            "BAWAG P.S.K.",
            "Credit Suisse",
            "WIR Bank",
            "Coop Bank",
            "UBS",
            // Karten
            "MasterCard",
            "VISA",
            // Paypal
            "PayPal",
            "PayPal blau",
            "PayPal grün",
            "PayPal rot",
            "PayPal orange",
            "PayPal pink",
            "PayPal grau",
            // Allgemein
            "Sparschwein",
            "Aktenordner",
            "Schatulle",
            "Kreditkarte",
            "Geschäft",
            "Privat",
            "Tastatur",
            "Abacus",
            "Onlinebanking",
            // 36 neue Icons von Herbert Held
            "GEFA Bank",
            "Barclays Bank",
            "1822direkt",
            "DenizBank",
            "Creditplus Bank",
            "AgrarB@nk",
            "Ethikbank",
            "DKB",
            "TARGOBANK",
            "Wüstenrot",
            "Deutsche Skatbank",
            "Ikano Bank",
            "Fidor (Legacy)",
            "Rabobank",
            "Moneyou",
            "GarantiBank",
            "OYAK ANKER Bank",
            "Audi Bank",
            "Volkswagen Bank",
            "BMW Bank",
            "IWBank",
            "Ziraat Bank",
            "VTB",
            "Bank of Scotland",
            "GE Capital",
            "ING-DiBa (v2)",
            "PrivatBank",
            "SWK Bank",
            "Triodos Bank",
            "Bank11",
            "Credit Europe Bank",
            "Merkur Privatbank",
            "Degussa Bank",
            "Umweltbank",
            "DHB Bank",
            "Consors Finanz / BNP Paribas",
            "Cronbank",
            "smava",
            "ABK",
            "Naspa",
            "NordFinanz Bank (Legacy)",
            "National-Bank",
            "KD-Bank",
            "Bank 1 Saar",
            "levoBank",
            "Haspa",
            "Bankhaus August Lenz (Legacy)",
            "Bankhaus Gebr. Martin",
            "MKB",
            "BBBank",
            "GLS Bank",
            "Berliner Bank (Legacy)",
            "Aktivbank",
            "ICICI Bank",
            "IKB",
            "MLP",
            "American Express",
            // Bitcoin und Kryptowährungen
            "Bitcoin",
            "Lightning",
            "BTCPay Server",
            "Bitcart",
            "Lipa",
            "Opago",
            "Monero",
            "Digitalwährung",
            // FinTechs
            "Wise",
            "Revolut",
            "Paypal (Icon)",
            "Holvi",
            "N26",
            "Tomorrow",
            "SumUp",
            "Alipay",
            "myPOS",
            "Neteller",
            "Western Union",
            "Payoneer",
            "Skrill",
            "Strike",
            "Wirex",
            "Glint",
            "Billie",
            // Karten
            "Diners Club",
            "Discover",
            "JCB",
            "Maestro",
            "UnionPay",
            "V PAY",
            // Neue Banken Österreich
            "Österr. Ärzte- u. Apothekerbank",
            "Addiko Bank",
            "Alpen Privatbank",
            "Anadi Bank",
            "Bank 99",
            "Bank Burgenland",
            "Bank Gutmann",
            "Bank Winter",
            "Schelhammer Capital Bank",
            "Bankhaus Spängler",
            "BKS Bank",
            "BTV Vier Länder Bank",
            "DADAT Bank",
            "easybank",
            "CA Autobank",
            "HYPO-Gruppe",
            "Kathrein Privatbank",
            "Kommunalkredit Invest",
            "Oberbank",
            "OeKB",
            "Partner Bank",
            "Renault Bank direkt",
            "Sparda-Bank (Österreich)",
            "Erste Bank",
            "VakifBank",
            "WSK Bank",
            // Schweizer Banken
            "Züricher Kantonalbank",
            "Bank Cler",
            "Raiffeisen (Schweiz)",
            // Weitere Banken
            "Consorsbank",
            "Fideuram Direct",
            "WIBank"
        };
    }
}
